---

# This docker-compose file is required to bind ports in development,
# since binding ports in regular compose file will ruin scaling
# in production. Due to how `ports` directive is merged with two files.
#
# This file is ignored in production, but
# it is automatically picked up in development with:
#
#  $ docker-compose up

version: "3.8"
services:
  db:
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      retries: 5
      interval: 10s
      timeout: 5s
      start_period: 10s

  json-server:
    container_name: json-server-container
    image: "json-server-image"
    build:
      context: .
      dockerfile: docker/json-server/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./tests/fixtures:/data
    command: json-server --watch db.json --host 0.0.0.0
    networks:
      - webnet
    env_file: ./config/.env

  web:
    ports:
      # We only bind ports directly in development:
      - "8000:8000"
    volumes:
      # We only mount source code in development:
      - .:/code
    build:
      # Needed for fixing permissions of files created by Docker
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    depends_on:
      - db
      - json-server

networks:
  # Fake API network:
  bitrixnet:
